// GENERATED by scripts/process-media.mjs — do not edit by hand.
// Source originals live in the owner's Drive; see QA-REPORT.md for the review notes.

export type ImageVariant = {
  base: string;
  widths: number[];
  width: number;
  height: number;
  jpgOnly: boolean;
};

export type ImageAsset = {
  id: string;
  project: string;
  kind: "image";
  /** Original file in the owner's Drive (05-ASSET-INVENTORY.csv). */
  driveId: string;
  /** SOURCE-MEDIA copy the export was made from. */
  copyId: string;
  alt: string;
  width: number;
  height: number;
  /** Path stem; files are `${base}-${w}.{avif,webp,jpg}`. */
  base: string;
  widths: number[];
  cropNotes: string;
  variants: Record<string, ImageVariant>;
};

export type VideoAsset = {
  id: string;
  project: string;
  kind: "video";
  driveId: string;
  copyId: string;
  alt: string;
  width: number;
  height: number;
  duration: number;
  mp4: string;
  webm: string;
  poster: string;
  cropNotes: string;
};

export const imageAssets: Record<string, ImageAsset> = {
  "E01-01": {
    "id": "E01-01",
    "project": "E01",
    "kind": "image",
    "driveId": "17IOfHla4bmW8wWjDx62F2uBXamZXENGh",
    "copyId": "1UQxyx7aBE_47pPU9e65BBHSie3gm91V6",
    "alt": "Pink balloon arch and ribbon fringe backdrop with light-up 16 numbers on a sunny patio",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e01/E01-01",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 4284x5712 at [0,171,4284x5355]. Home hero. Desktop 3:2 and mobile 4:5 keep the full arch and the light-up 16. Foreground shrub trimmed in the 3:2 crop. No people in frame.",
    "variants": {
      "hero-desktop": {
        "base": "/images/portfolio/e01/E01-01-hero-desktop",
        "widths": [
          800,
          1600,
          2400
        ],
        "width": 2400,
        "height": 1600,
        "jpgOnly": false
      },
      "hero-mobile": {
        "base": "/images/portfolio/e01/E01-01-hero-mobile",
        "widths": [
          800,
          1200
        ],
        "width": 1200,
        "height": 1500,
        "jpgOnly": false
      },
      "og": {
        "base": "/images/portfolio/e01/E01-01-og",
        "widths": [
          1200
        ],
        "width": 1200,
        "height": 630,
        "jpgOnly": true
      }
    }
  },
  "E01-03": {
    "id": "E01-03",
    "project": "E01",
    "kind": "image",
    "driveId": "1orcVrOJuCWI-irqpYHdwa_uGLliy-GRH",
    "copyId": "1Yam8XbBsajBOcqCdd1XklECh87hnm5p3",
    "alt": "Ribbon fringe backdrop framed by pink balloons beside light-up 16 numbers",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e01/E01-03",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 4284x5712 at [0,228,4284x5355]. 4:5 straight-on. No people in frame.",
    "variants": {}
  },
  "E01-04": {
    "id": "E01-04",
    "project": "E01",
    "kind": "image",
    "driveId": "1fFYcuj9WxV0yl1Ize6MrobRSDfKJ_BMM",
    "copyId": "1Z9UEg2BlcUQ3OFgnYfN9IVNR305KTj-4",
    "alt": "Angled view of a pink balloon arch and ribbon backdrop",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e01/E01-04",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 3024x4032 at [0,161,3024x3780]. 4:5. No people in frame.",
    "variants": {}
  },
  "E01-05": {
    "id": "E01-05",
    "project": "E01",
    "kind": "image",
    "driveId": "1iQiUcqE5_Ks2IGe6XMnAwi8qEVrmA-SY",
    "copyId": "1pJ9TyJgFZqMcrB-DI_tp0GCp4-GL2HrR",
    "alt": "Organic pink balloon arch framing French doors on a stone patio",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e01/E01-05",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 4284x5712 at [0,228,4284x5355]. 4:5. Glass shows only a dark, unidentifiable reflection of the photographer.",
    "variants": {}
  },
  "E01-06": {
    "id": "E01-06",
    "project": "E01",
    "kind": "image",
    "driveId": "1UvHzAgvGlbmR7gXk465qtTSV0xNr0gJU",
    "copyId": "1zc324wfameMPo-KEv-OuQjr67a9_kNy_",
    "alt": "Pink balloon arch in layered shades of pink",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e01/E01-06",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 4284x5712 at [0,228,4284x5355]. 4:5. Glass shows only dark, unidentifiable reflections.",
    "variants": {}
  },
  "E01-07": {
    "id": "E01-07",
    "project": "E01",
    "kind": "image",
    "driveId": "1CDaRGWPyxRazg01QB-_sOabpudo6c8Tu",
    "copyId": "1s74xZ1RJT0qIvXPeJILPBhqoZtXtuZiP",
    "alt": "Pink organic balloon arch at a brick doorway",
    "width": 1600,
    "height": 2000,
    "base": "/images/portfolio/e01/E01-07",
    "widths": [
      800,
      1600
    ],
    "cropNotes": "4:5 crop from 2080x3120 at [0,250,2080x2600]. Source is 2:3 portrait (EXIF orientation 8, rotated). 4:5 crop. No people in frame.",
    "variants": {}
  },
  "E01-08": {
    "id": "E01-08",
    "project": "E01",
    "kind": "image",
    "driveId": "1JYGTF4fgV4n3ZjTNIGPfzzdxaouXV3ie",
    "copyId": "1z5PnFdsmFZfiu09G3tkpYaaay8SAqD7Z",
    "alt": "Pink balloon arch mid-installation with a step ladder beside it",
    "width": 1600,
    "height": 2000,
    "base": "/images/portfolio/e01/E01-08",
    "widths": [
      800,
      1600
    ],
    "cropNotes": "4:5 crop from 2080x3120 at [0,374,2080x2600]. 4:5, crop keeps the step ladder. No people in frame.",
    "variants": {}
  },
  "E01-09": {
    "id": "E01-09",
    "project": "E01",
    "kind": "image",
    "driveId": "1A9dWUiLkCHRTPbio7-FbthdtLucZ3VYi",
    "copyId": "1DKxA2wHD2Yp29TjgdZzoEjuxkhm2WhD7",
    "alt": "Pink balloon clusters along a balcony railing overlooking trees",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e01/E01-09",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 4284x5712 at [0,0,4284x5355]. 4:5 detail. No people in frame; no house or street identifiers.",
    "variants": {}
  },
  "E02-01": {
    "id": "E02-01",
    "project": "E02",
    "kind": "image",
    "driveId": "1FJfnMfqQDyYMp0Hs9AGWbay5t07ak45L",
    "copyId": "1ndQybpXrr59glZAr8oYG5a4ODuaR8K4H",
    "alt": "Game-night balloon column with playing cards and oversized dice beside a welcome sign",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e02/E02-01",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 3024x4032 at [0,121,3024x3780]; blurred 1 region(s). 4:5. Honoree's name on the welcome sign was legible and is blurred.",
    "variants": {
      "og": {
        "base": "/images/portfolio/e02/E02-01-og",
        "widths": [
          1200
        ],
        "width": 1200,
        "height": 630,
        "jpgOnly": true
      }
    }
  },
  "E02-02": {
    "id": "E02-02",
    "project": "E02",
    "kind": "image",
    "driveId": "1wfPuKVHTI-pAGCyTxOM8N7ipdZ9DU8Yz",
    "copyId": "1Zfpc64wqxps4IOzZFDBMA0uv6BGLhiiZ",
    "alt": "Black, silver, purple and pink balloon column with stacked dice",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e02/E02-02",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 3024x4032 at [0,121,3024x3780]; blurred 1 region(s). 4:5. Honoree's name on the welcome sign was legible and is blurred.",
    "variants": {}
  },
  "E03-01": {
    "id": "E03-01",
    "project": "E03",
    "kind": "image",
    "driveId": "1TQxWKoKZU3yWkyLYukn-fcOl7WkCUCTU",
    "copyId": "1ryvRy4i-XTRMRaWwTRMy0lkAk0zD6te4",
    "alt": "Teal and lime balloon garlands framing a purple shimmer-wall backdrop",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e03/E03-01",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 3024x4032 at [0,252,3024x3780]. Manifest asked for 3:2; the source is 3:4 portrait and a 3:2 crop would cut the garlands, so 4:5 with the ceiling trimmed. Panel text is the ministry team name only; no church named.",
    "variants": {
      "og": {
        "base": "/images/portfolio/e03/E03-01-og",
        "widths": [
          1200
        ],
        "width": 1200,
        "height": 630,
        "jpgOnly": true
      }
    }
  },
  "E03-02": {
    "id": "E03-02",
    "project": "E03",
    "kind": "image",
    "driveId": "11TiTOSgsOX-4MQ_EvO5fd_j_J1TOWYq5",
    "copyId": "16HtrQm3tJQwx9j8zz625SzBJTXWVlmC-",
    "alt": "Balloon garlands in teal and lime around a purple sequin wall",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e03/E03-02",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 3024x4032 at [0,252,3024x3780]. 4:5 with ceiling trimmed (source is portrait; see E03-01).",
    "variants": {}
  },
  "E03-03": {
    "id": "E03-03",
    "project": "E03",
    "kind": "image",
    "driveId": "1ISgpAesyLAihVgqufn9iL8Jx0aFZ-8Dz",
    "copyId": "1C-Y1hcMwf0v29GcClDTXoo-RM2bECT3K",
    "alt": "Close view of teal and lime balloon garland beside a purple panel",
    "width": 2400,
    "height": 3000,
    "base": "/images/portfolio/e03/E03-03",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:5 crop from 3024x4032 at [0,252,3024x3780]. 4:5.",
    "variants": {}
  },
  "E04-02": {
    "id": "E04-02",
    "project": "E04",
    "kind": "image",
    "driveId": "1hGzpLx4NnRPo2x_3ocNYL8-z_DEUixHG",
    "copyId": "1u4UX5et-3sBJazaZaRiw1fofNArPOfiY",
    "alt": "Rose flower wall framing pink sequin panels",
    "width": 2400,
    "height": 1800,
    "base": "/images/portfolio/e04/E04-02",
    "widths": [
      800,
      1600,
      2400
    ],
    "cropNotes": "4:3 crop from 4032x3024 at [323,121,3709x2782]. 4:3. Left edge trimmed to remove a partial guest at the frame edge.",
    "variants": {
      "og": {
        "base": "/images/portfolio/e04/E04-02-og",
        "widths": [
          1200
        ],
        "width": 1200,
        "height": 630,
        "jpgOnly": true
      }
    }
  }
};

export const videoAssets: Record<string, VideoAsset> = {};
